name: crazycat_controller
description: CrazyCat Controller - App para controle de dispositivos.
publish_to: 'none'
version: 3.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.1.0
  flutter_bluetooth_serial_ble: ^0.5.0
  permission_handler: ^11.0.1
  shared_preferences: ^2.2.2
  google_fonts: ^5.1.0
  provider: ^6.1.1
  connectivity_plus: ^5.0.2
  network_info_plus: ^4.1.0
  usb_serial: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
